### ISSUE TITLE
REST-API authentication support

### ISSUE THREAD

**Issue by mbanck** [dalibo/check_patroni#52]
`check-patroni` seems to query the REST API of the Patroni nodes. It has support for SSL connections, however, it seems authentication support is missing? This would be an example Patroni conf snippet:

```
restapi:
  listen: 0.0.0.0:8008
  connect_address: 10.0.0.1:8008
  authentication:
    username: patroni
    password: foo
```
